### PR TITLE
Add influxdb v2 output

### PR DESCRIPTION
**Pull request by koleson**
Hi there!  I've been using `weatherflow-udp-listener` for the past few years with great results.  I added InfluxDB v2 support to my local copy, but never tried to upstream it.  I saw this new repo when migrating to a new machine and figured it would be a good time to do upstream this!

- Adds InfluxDB v2 support.  It uses a different auth model, so I did not attempt to reuse the existing arguments.  The client library it uses is officially supported by InfluxData.  The client also has support for pre-2.0 InfluxDB - I did not try to migrate existing InfluxDB 1.x output to the new library but would be happy to do so.
- Args are not globally available.  This caused a few problems with configuration that are now fixed by passing args into the publishers
    - Fixes issues with specifying custom MQTT broker addresses
    - Fixes issues with addresses/credentials for InfluxDB
- other minor "fixes"
    - fixed a date format in a comment
    - conditionalized some logging that seemed intended for verbose mode

Unresolved:
- I wound up using the MQTT broker address specified in the command line arguments everywhere rather than the existing `mqtt_host` / `MQTT_HOST` global.  Should the MQTT broker address be required?  Or should it default to `mqtt` when not specified?

### CODE REVIEW

**Comment by vinceskahan** [comment]
Thanks.  Good stuff. Thanks for having each change in a separate commit.  That helps a lot.

Long answer follows.

There's an [old not-merged PR from 2020](https://github.com/vinceskahan/weatherflow-udp-listener/pull/7) to add v2 support that I never merged into the original listener.  I didn't merge it back then due to not having time to even test it.

* please check out that PR and see if there's anything in there that you might want to use in your PR

Re: MQTT - I like it the way it was, with a default (mqtt) that the user could supersede with a command-line option.

* please revert that change

Re: the date format in the comment, I'd like to continue to use the way *I* indicate dates, for better or worse.

* please revert that change

When/if you get to done:

* need the README file updated to match of course

Unrelated - I have some unrelated changes in progress on another branch that I just pushed up, but they shouldn't affect you adding v2 influxdb support.  I also need to add a short Changelog and CREDITS couple of files, which I'll do real soon now.

I have more time to test these days if you get to a point where you think you're done with this PR and we can get it finalized.  Thanks again of course.

**Comment by koleson** [comment]
All sounds good - I'll update this PR in the coming days.  I'll take a look at your branch as well.

**Comment by koleson** [comment]
Ha, old not-merged PR was mine, I guess I tried to upstream at the time I updated it!

That code has been running on my machine since that PR up until last Friday, so at least it got some exercise.

**Comment by vinceskahan** [comment]
Thanks.  I created a couple Issues in the repo so I don't forget my part.

I also added a 'develop' branch ala git-flow that new features should be merged to first.  I'm not going to go nutso with full git-flow, but basically I'd like to keep stuff in-work separate from main (the released stuff).  So feature(s) => develop and then once things are good and integration-tested I'll do develop=>main and release/tag there.

Might as well get at least a little formal so this stuff doesn't go boom in a merge massacre :-)

**Comment by koleson** [comment]
> Re: MQTT - I like it the way it was, with a default (mqtt) that the user could supersede with a command-line option.

Just remembered why I made this change:  I think there was an unintentional behavior change here on the custom-settings case when moving from Python 2.x to Python 3.  Assignment to a shadowed variable name within a function worked naively (overwrote the global variable) in Python 2.x; In Python 3, assignment to a shadowed variable name does not modify the global.

From my opinionated armchair, it might be better to use null-coalescing logic to set defaults in `args` within `main` to avoid ambiguity, but I've got the unopinionated minimum-change commit coming down the pipe in a moment.

**Comment by koleson** [comment]
TODO:  update README.

**Comment by vinceskahan** [comment]
It's looking pretty good.  Thanks for catching that indentation error.  I'm not fully testing all the possible option combinations here and missed noticing that one.

Add the README snippet and we can call this one good.   Just copy/tweak the existing example and we can call it good.

**Comment by vinceskahan** [comment]
published to test-pypi if you want to give it a try.  I can bump the ver to 5.1 and release officially after you give me the word.

**Comment by koleson** [comment]
i'll pull it down and let it run for a few hours!

**Comment by koleson** [comment]
haven't seen any issues on the test-pypi version - my config includes a custom mqtt broker hostname and influxdb2 target.

**Comment by vinceskahan** [comment]
ok, I'll bump the ver and take the beta indication off and release to pypi this weekend.  Thanks again !

**Comment by koleson** [comment]
thank you!

**Comment by vinceskahan** [comment]
I'm closing this one.  Pushed to prod pypi.  Thanks again for reminding me and testing !

**Pull request merged**
